---
title: "project_draft"
author: "Wanjia Guo"
date: "2/16/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

## Loading data and packages

```{r setup, include=FALSE}

library(tidyverse)
library(ggplot2)
library(dplyr)
library(colorblindr)

theme_set(theme_minimal())

files <- fs::dir_ls(here::here("data", "project"))

obs <- gsub(".+project/(.+)\\.csv", "\\1", files)
purrr::map2(obs, files, ~{
   assign(.x, read_csv(.y), envir = .GlobalEnv)
})
```

## How different songs’ properties influence it’s popularity?

```{r}
range(data$danceability)
range(data$duration_ms)
range(data$tempo)
range(data$speechiness)

data1 = data %>% 
  select(id, popularity, year, danceability, duration_ms, tempo, speechiness) %>% 
  mutate(duration = 
           (duration_ms-min(duration_ms))/(max(duration_ms)-min(duration_ms))) %>% 
  select(-duration_ms) %>% 
  mutate(tempo = (tempo-min(tempo))/(max(tempo)-min(tempo)))
  

fig1_data = data1 %>% select(-year) %>% 
  mutate(danceability = cut(danceability, 50, labels=FALSE),
         duration = cut(duration, 50, labels=FALSE),
         tempo = cut(tempo, 50, labels=FALSE),
         speechiness = cut(speechiness, 50, labels=FALSE)) %>% 
  pivot_longer(cols = danceability:duration, 
               names_to = "property") %>% 
  group_by(property, value) %>% 
  summarise(popularity_median = median(popularity)) %>% 
  mutate(property = factor(property, levels=c("danceability",
                                              "tempo",
                                              "speechiness",
                                              "duration")))

ggplot(fig1_data, aes(x=value, y=popularity_median, group=property)) + 
  geom_ribbon(aes(ymin = 0, ymax = popularity_median, fill=property), alpha=0.6) + 
  labs(x = "Normalized Value (0-30)", y = "Median Popularity (0-100)") + 
  scale_fill_OkabeIto()

# Comments from Meg: First of all, I love the way you used transparency to overlay these groups on top of each other, and especially that you used a colorblind-friendly color scale.
# Meg: Overall, I think this is a super interesting question to be investigating, but having the properties overlaid on top of each other actually may make it more difficult to interpret. I wonder if using facet_wrap(~property) may provide a clearer way of comparing among them. 
```

## How does songs’ properties change over time?

```{r}

fig2_data = data1 %>% 
  mutate(decades = year - year %% 10 ) %>% 
  select(-c(popularity, year)) %>% 
  pivot_longer(cols = danceability:duration, 
               names_to = "property") %>% 
  group_by(property, decades) %>% 
  summarise(mean = mean(value))

ggplot(fig2_data, aes(x=decades, y=property, fill=mean)) + geom_tile() +
  scale_fill_viridis_c(option = "A") + 
  labs(y="Property", x="Mean for each decade") + 
  theme(legend.position = "top")

# Meg: I really love the use of a heatmap to visualize this! It looks super elegant and it's very easy to see the trends over time (I especially like how clear it is to see the peak of danceability in the 1950s). 
# Meg: It may be more aesthetically pleasing to arrange the properties in order of intensity of heat (maybe duration, speechiness, tempo, danceability). 
```


## The most popular artist over time

```{r}

library(gganimate)

artist_data = data %>% 
  select(popularity, artists, year) %>% 
  mutate(artists =  gsub("\\[|\\]", "", artists)) %>% 
  separate_rows(artists, sep = ", ") %>% 
  mutate(artists =  gsub("'", "", artists)) %>% 
  mutate(artists =  gsub('"', '', artists))


fig3_data = artist_data %>% 
  mutate(decades = year - year %% 10 ) %>% 
  mutate(year = ifelse(year < 1990, decades, year)) %>% 
  group_by(year, artists) %>% 
  summarise(mean_popularity = mean(popularity)) %>% 
  arrange(year, desc(mean_popularity)) %>% 
  mutate(rank = 1:n()) %>% 
  filter(rank <= 10)


my_theme <- theme_classic(base_family = "Times") +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  theme(axis.line.y = element_blank()) +
  theme(legend.background = element_rect(fill = "gainsboro")) +
  theme(plot.background = element_rect(fill = "gainsboro")) +
  theme(panel.background = element_rect(fill = "gainsboro"))

fig3 = ggplot(fig3_data) +  
  aes(xmin = 18 ,  
      xmax = mean_popularity) +  
  aes(ymin = rank - .45,  
      ymax = rank + .45,  
      y = rank) +  
  facet_wrap(~ year) +  
  geom_rect(alpha = .7) +
  scale_x_continuous(  
    limits = c(-50, 100),
    breaks = c(0, 20, 40, 60, 80, 100)) + 
  geom_text(col = "gray13",  
            hjust = "right",  
            aes(label = artists),  
            x = 10) + 
  scale_y_reverse() + 
  labs(x = 'Popularity (0-100)', y = '') +  
  my_theme 


fig3 = fig3 +  
  facet_null() + 
  geom_text(x = 50 , y = -5,
            family = "Times",
            aes(label = as.character(year)),
            size = 25, col = "grey18", alpha=0.5) + 
  aes(group = artists) +  
  transition_states(year,
                    transition_length = 1,
                    state_length = 4)

animate(fig3, fps=1)

# Meg: I've never worked with gganimate or tried to animate visualizations, so I'm pretty blown away by this and will definitely look into using it for my own research!
# Meg: I am getting a warning message here: "file_renderer failed to copy frames to the destination directory" but I can still see the visualization in your HTML. I'm not sure if this is something wrong with my computer?
# Meg: This visualization is truly so cool and innovative, and I love the way that you centered the year so it feels like some sort of time machine.
# Meg: I found myself wanting to read all of the names for each year and feeling crunched for time. I wonder if this visualization might be well-paired with a bar chart that showed all of these artists in relation to each other (instead of grouping by year, but maybe with each year being shown in a different color). That way, when you see the animation you'd also be able to refer back to the overall bar chart. Obviously that could also be an entire other viz, though, so really no pressure to add it!
```


